Update CHANGELOG.md
mapbox/mapbox-maps-ios pull request #1507
Opened 2022-08-03 00:34 UTC by ZiZasaurus

changelog entry for exposing image property for compass ornament was linked to incorrect ticket.

## Pull request checklist:
 - [ ] Describe the changes in this PR, especially public API changes.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
    
 - [ ] Write tests for all new functionality. If tests were not written, please explain why.
 - [ ] Add documentation comments for any added or updated public APIs.
 - [ ] Add any new public, top-level symbols to the Jazzy config's `custom_categories` (scripts/doc-generation/.jazzy.yaml)
 - [ ] Add a changelog entry to to bottom of the relevant section (typically the `## main` heading near the top).
 - [ ] Update the guides (internal access only), README.md, and DEVELOPING.md if their contents are impacted by these changes.
 - [ ] If this PR is a `v10.[version]` release branch fix / enhancement, merge it to `main` first and then port to `v10.[version]` release branch.

PRs must be submitted under the terms of our Contributor License Agreement [CLA](https://github.com/mapbox/mapbox-maps-ios/blob/main/CONTRIBUTING.md#contributor-license-agreement).

2022-08-03 03:30 UTC, maios requested changes

2022-08-03 03:30 UTC, maios commented on CHANGELOG.md
> +* Expose image property for compass ornament. ([#1466](https://github.com/mapbox/mapbox-maps-ios/pull/1468))
```suggestion
* Expose image property for compass ornament. ([#1468](https://github.com/mapbox/mapbox-maps-ios/pull/1468))
```

2022-08-04 03:19 UTC, maios approved these changes

2022-08-04 06:28 UTC, evil159 approved these changes

2022-08-04 08:53 UTC, OdNairy approved these changes

2022-08-04 13:17 UTC, merged