Resolve issue where selected view annotation is not moved to correct z-order
mapbox/mapbox-maps-ios pull request #1607
Opened 2022-09-28 15:05 UTC by ZiZasaurus

## Pull request checklist:
 - [ ] Describe the changes in this PR, especially public API changes.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
    
 - [ ] Write tests for all new functionality. If tests were not written, please explain why.
 - [ ] Add documentation comments for any added or updated public APIs.
 - [ ] Add any new public, top-level symbols to the Jazzy config's `custom_categories` (scripts/doc-generation/.jazzy.yaml)
 - [ ] Add a changelog entry to to bottom of the relevant section (typically the `## main` heading near the top).
 - [ ] Update the guides (internal access only), README.md, and DEVELOPING.md if their contents are impacted by these changes.
 - [ ] If this PR is a `v10.[version]` release branch fix / enhancement, merge it to `main` first and then port to `v10.[version]` release branch.

PRs must be submitted under the terms of our Contributor License Agreement [CLA](https://github.com/mapbox/mapbox-maps-ios/blob/main/CONTRIBUTING.md#contributor-license-agreement).

2022-09-28 20:03 UTC, pjleonard37 approved these changes

2022-09-29 02:59 UTC, maios requested changes
correct me if I'm wrong but the order of the views is decided in `DelegatingViewAnnotationPositionsUpdateListenerDelegate`, upon receiving changes in view annotations (adding/removing/updating), `mapboxMap` will notify its delegate about new placement of annotation views. I think the test should setup similar to this test below
https://github.com/mapbox/mapbox-maps-ios/blob/6ac39ecdf77ce868c6941036d6a4cc55f0421cfd/Tests/MapboxMapsTests/Annotations/ViewAnnotationManagerTests.swift#L276

2022-09-29 02:59 UTC, maios commented on Tests/MapboxMapsTests/Annotations/ViewAnnotationManagerTests.swift
> +        try? manager.update(annotationViewA, options: ViewAnnotationOptions(selected: true))
this function will not call to `mapboxMap.addViewAnnotation(withId:options:)`, therefore the following assertion does not make sense, the stubbed invocation is made in the previous step of this test case and has not been reset, so, with or without this line the test would always succeed

2022-10-04 14:47 UTC, ZiZasaurus commented on Tests/MapboxMapsTests/Annotations/ViewAnnotationManagerTests.swift
> +        XCTAssertEqual(mapboxMap.addViewAnnotationStub.invocations.last?.parameters.id, "test-id2")
Looks like bringSubviewToFront/sendToBack doesn't change zPosition, but it does move subview position among the subviews so I referenced the array/ array order instead.

2022-10-05 06:58 UTC, maios approved these changes
Please check if 2 added files in Debug App and Example Apps are intended

2022-10-05 08:16 UTC, evil159 approved these changes

2022-10-05 13:52 UTC, merged