Resolve issue with simultaneous recognition of tap gesture
mapbox/mapbox-maps-ios pull request #1712
Opened 2022-11-09 17:03 UTC by ZiZasaurus

## Pull request checklist:
 - [ ] Describe the changes in this PR, especially public API changes.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
    
 - [ ] Write tests for all new functionality. If tests were not written, please explain why.
 - [ ] Add documentation comments for any added or updated public APIs.
 - [ ] Add any new public, top-level symbols to the Jazzy config's `custom_categories` (scripts/doc-generation/.jazzy.yaml)
 - [ ] Add a changelog entry to to bottom of the relevant section (typically the `## main` heading near the top).
 - [ ] Update the guides (internal access only), README.md, and DEVELOPING.md if their contents are impacted by these changes.
 - [ ] If this PR is a `v10.[version]` release branch fix / enhancement, merge it to `main` first and then port to `v10.[version]` release branch.

PRs must be submitted under the terms of our Contributor License Agreement [CLA](https://github.com/mapbox/mapbox-maps-ios/blob/main/CONTRIBUTING.md#contributor-license-agreement).

2022-11-10 09:55 UTC, evil159 requested changes
The fix looks good 👍 Tests are missing though 😕

2022-11-10 10:53 UTC, maios commented on Sources/MapboxMaps/Gestures/GestureHandlers/SingleTapGestureHandler.swift
> +        return gestureRecognizer is UITapGestureRecognizer
should we also check condition of `otherGestureRecognizer` being of type `UITapGestureRecognizer`?
and maybe a check `gestureRecognizer === self.gestureRecognizer` is better here and more consistent to other GestureHandler i.e https://github.com/mapbox/mapbox-maps-ios/blob/main/Sources/MapboxMaps/Gestures/GestureHandlers/PinchGestureHandler.swift#L124

2022-11-10 13:36 UTC, pjleonard37 commented
👍  - this resolved the issue for me. Do we need to adjust the other gesture handlers as well? I'm specifically thinking about LongPress, but others may need to be adjusted. 

Additionally, can we expand tests across the gesture handlers to catch these behavior changes?

2022-11-10 18:11 UTC, persidskiy approved these changes
lgtm

2022-11-11 08:09 UTC, maios approved these changes
🎉

2022-11-11 09:16 UTC, evil159 approved these changes
🔥

2022-11-11 11:56 UTC, pjleonard37 approved these changes

2022-11-11 14:11 UTC, merged