Update analyze.yml to accept executor as input.
mapbox/mapbox-maps-ios pull request #2116
Opened 2024-02-09 00:13 UTC by billyjbryant

### Description

Updates the CodeQL Workflow to accept the executor as input, allowing provision for self-hosted runners when re-using the workflow.

## Pull request checklist:
 - [x] Describe the changes in this PR, especially public API changes.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
    
 - [ ] Write tests for all new functionality. Put tests in correct [Test Plan](https://github.com/mapbox/mapbox-maps-ios/tree/main/Tests/TestPlans) (Unit, Integration, All)
   - [ ] If tests were not written, please explain why.
 - [ ] Add documentation comments for any added or updated public APIs.
 - [ ] Add any new public, top-level symbols to the Jazzy config's `custom_categories` (scripts/doc-generation/.jazzy.yaml)
 - [ ] Add a changelog entry to to bottom of the relevant section (typically the `## main` heading near the top).
 - [ ] Update the guides (internal access only), README.md, and DEVELOPING.md if their contents are impacted by these changes.
 - [ ] If this PR is a `v10.[version]` release branch fix / enhancement, merge it to `main` first and then port to `v10.[version]` release branch.

PRs must be submitted under the terms of our Contributor License Agreement [CLA](https://github.com/mapbox/mapbox-maps-ios/blob/main/CONTRIBUTING.md#contributor-license-agreement).

2024-02-09 00:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mapbox/mapbox-maps-ios?pullRequest=2116) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mapbox/mapbox-maps-ios?pullRequest=2116) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mapbox/mapbox-maps-ios?pullRequest=2116) it.</sub>

2024-02-09 12:00 UTC, aleksproger requested changes
Move changes to internal repo after testing here

2024-02-09 19:01 UTC, billyjbryant commented
> Move changes to internal repo after testing here

@aleksproger : I'm not certain what you are asking to be changed? PR https://github.com/mapbox/mapbox-maps-ios-internal/pull/2022 has already been opened for internal repo changes that are required; however, this PR is a pre-req of that PR.

2024-02-09 20:31 UTC, ThibaudLopez approved these changes

2024-02-09 20:31 UTC, merged

2024-02-14 08:50 UTC, OdNairy commented
I have to force-remove the commit as it broke our infrastructure. 
Please, do not merge PRs into maps-ios repository – it has to go through the internal infrastructure instead.