Fix an issue where updating compass visibility doesn't take effect
mapbox/mapbox-maps-ios pull request #258
Opened 2021-04-12 21:15 UTC by jmkiley

PRs must be submitted under the terms of our Contributor License Agreement [CLA](https://github.com/mapbox/mapbox-maps-ios/blob/main/CONTRIBUTING.md#contributor-license-agreement).

Fixes: < Link to related issues that will be fixed by this pull request, if they exist >

## Pull request checklist:
 - [ ] Briefly describe the changes in this PR.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
 - [ ] Write tests for all new functionality. If tests were not written, please explain why.
 - [ ] Add example if relevant.
 - [ ] Document any changes to public APIs.
 - [ ] Apply changelog label ('breaking change', 'bug :beetle:', 'build', 'docs', 'feature :green_apple:', 'performance :zap:', 'testing :100:') or use the label 'skip changelog'
 - [ ] Add an entry inside this element for inclusion in the `mapbox-maps-ios` changelog: `<changelog></changelog>`.
 - [ ] Update the migration guide, API Docs, Markdown files - Readme, Developing, etc

### Summary of changes

This PR:
- Renames `OrnamentOptions.compassVisiblity` to `OrnamentOptions.compassVisibility`.
- Fixes an issue where updating the visibility of the compass doesn't take effect. There are two components to the fix:
    - Update existing ornaments when the `OrnamentConfig` is updated. Note that this fix currently assumes that there will only be one ornament of a given type on the map at a time.
    - Stores the positions and margins for supported ornaments. This is in part because `OrnamentConfig`'s init only takes updates into account when they have corresponding positions and margins.

### User impact (optional)

- The rename of `OrnamentOptions.compassVisibility` impacts users currently using that property.

2021-04-14 18:52 UTC, neelmistry94 requested changes

2021-04-14 18:52 UTC, neelmistry94 commented on Sources/MapboxMaps/Ornaments/ScaleBar/MapboxScaleBarOrnamentView.swift
> +            self.alpha = 0
`MapboxScaleBarOrnamentView` is of type `UIView`. Use the `isHidden` property instead

2021-04-14 18:52 UTC, neelmistry94 commented on Sources/MapboxMaps/Ornaments/ScaleBar/MapboxScaleBarOrnamentView.swift
> +            let maximumDistance: CLLocationDistance = Double(maximumWidth) * unitsPerPoint
With the above change, alter the `isHidden` property to be `false`

2021-04-14 19:59 UTC, macdrevx commented
@jmkiley you've definitely identified the root cause of this bug (`Ornament.view` is never set). In terms of fixing it, I think we should take a step back as a team and reevaluate the architecture of the ornaments implementation. We may decide that it'd be better to make a larger change to simplify things internally instead of proceeding with trying to patch this specific issue.

2021-04-16 20:32 UTC, neelmistry94 approved these changes

2021-04-23 14:12 UTC, macdrevx commented
Closing in favor of #288

2021-04-23 14:12 UTC, closed without merging