Update Gesture Manager Delegate methods
mapbox/mapbox-maps-ios pull request #697
Opened 2021-09-22 13:58 UTC by jmkiley

PRs must be submitted under the terms of our Contributor License Agreement [CLA](https://github.com/mapbox/mapbox-maps-ios/blob/main/CONTRIBUTING.md#contributor-license-agreement).

Fixes: < Link to related issues that will be fixed by this pull request, if they exist >

## Pull request checklist:
 - [ ] Briefly describe the changes in this PR.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
 - [ ] Write tests for all new functionality. If tests were not written, please explain why.
 - [ ] Add example if relevant.
 - [ ] Document any changes to public APIs.
 - [ ] Apply changelog label ('breaking change', 'bug :beetle:', 'build', 'docs', 'feature :green_apple:', 'performance :zap:', 'testing :100:') or use the label 'skip changelog'
 - [ ] Add an entry inside this element for inclusion in the `mapbox-maps-ios` changelog: `<changelog></changelog>`.
 - [ ] Update the migration guide, API Docs, Markdown files - Readme, Developing, etc

### Summary of changes
This PR:
- Renames `GestureManagerDelegate.gestureBegan(for:)` to `GestureManagerDelegate.gestureManager(_:didBegin:)`. 
- Adds delegate methods for when the gesture and drifts end to `GestureHandlerDelegate` and `GestureManagerDelegate`.
### User impact (optional)

2021-09-22 17:30 UTC, neelmistry94 commented on CHANGELOG.md
> +* `GestureManagerDelegate.gestureBegan(for:)` has been renamed to `GestureManagerDelegate.gestureManager(_:didBegin:)`. Added the public delegate methods ``GestureManagerDelegate.gestureManager(_:did
Maybe split this changelog into two lines. The "Added the public delegate methods..." should be a separate entry.

Also looks like there is an issue with back ticks here

2021-09-22 17:31 UTC, neelmistry94 commented on Sources/MapboxMaps/Gestures/GestureHandlers/DoubleTapToZoomGestureHandler.swift
> +                                             completion: { [weak self] _ in
I believe @macdrevx has a PR that makes ease a discardable result. So maybe land that PR first and then you should rebase

2021-09-22 17:32 UTC, neelmistry94 approved these changes

2021-09-22 20:52 UTC, macdrevx requested changes
This is on the right track. I haven't reviewed tests yet, but let's address this batch of feedback first.

2021-09-22 20:52 UTC, macdrevx commented on Sources/MapboxMaps/Gestures/GestureHandlers/GestureHandler.swift
> +    func driftEnded(for gestureType: GestureType)
Let's use the word deceleration instead of drift for consistency

2021-09-22 20:52 UTC, macdrevx commented on Sources/MapboxMaps/Gestures/GestureHandlers/PanGestureHandler.swift
> +            delegate?.gestureEnded(for: .pan, willDecelerate: true)
We don't always decelerate this gesture. See the comment just after this line.

2021-09-22 20:52 UTC, macdrevx commented on Sources/MapboxMaps/Gestures/GestureManager.swift
> +    func gestureManager(_ gestureManager: GestureManager, didEnd gestureType: GestureType, willDecelerate: Bool)
I'm wondering whether we should rename this to "willAnimate" so that it's a more accurate description for all gestures. Let's discuss this together.

2021-09-22 20:52 UTC, macdrevx commented on Sources/MapboxMaps/Gestures/GestureManager.swift
> +    /// Informs the delegate that a gesture has begun. Could be used to cancel camera tracking.
Preexisting, but I wonder if we should remove the "this could be used to cancel camera tracking". Is that still relevant?

2021-09-23 12:39 UTC, macdrevx commented on Sources/MapboxMaps/Gestures/GestureManager.swift
> +    func gestureManager(_ gestureManager: GestureManager, didEnd gestureType: GestureType, willDecelerate: Bool)
Decision: we'll rename to `willAnimate`.

Please rename the 3rd method and GestureHandlerDelegate methods accordingly

2021-09-23 12:39 UTC, macdrevx commented on Sources/MapboxMaps/Gestures/GestureHandlers/GestureHandler.swift
> +    func driftEnded(for gestureType: GestureType)
Superseded by https://github.com/mapbox/mapbox-maps-ios/pull/697#discussion_r714753031

2021-09-23 17:21 UTC, macdrevx commented on Sources/MapboxMaps/Gestures/GestureManager.swift
> +    func gestureManager(_ gestureManager: GestureManager, didEndDeceleratingFor gestureType: GestureType)
Let's update this for consistent terminology. "didEndAnimatingFor"

2021-09-23 17:22 UTC, macdrevx commented on Sources/MapboxMaps/Gestures/GestureHandlers/GestureHandler.swift
> +    func driftEnded(for gestureType: GestureType)
Let's use consistent terminology here too "animationEnded"

2021-09-23 17:50 UTC, macdrevx commented on Sources/MapboxMaps/Gestures/GestureManager.swift
> +    /// has completed. Does not indicate whether gesture-based animations have completed.
I would remove "Does not indicate whether gesture-based animations have completed."

2021-09-23 17:50 UTC, macdrevx commented on Sources/MapboxMaps/Gestures/GestureManager.swift
> +    /// has completed. Does not indicate whether gesture-based animations have completed.
I think the rest is sufficiently clear

2021-09-23 17:52 UTC, macdrevx commented on Tests/MapboxMapsTests/Gestures/GestureHandlers/DoubleTapToZoomInGestureHandlerTests.swift
> +        }
Mark this test case with `throws` and then change these lines to

```suggestion
            let willAnimate = try XCTUnwrap(delegate.gestureEndedStub.parameters.first?.willAnimate)
            XCTAssertTrue(willAnimate)
```

2021-09-23 17:53 UTC, macdrevx commented on Tests/MapboxMapsTests/Gestures/GestureHandlers/DoubleTapToZoomInGestureHandlerTests.swift
>      }
Need to test that DoubleTapToZoomHandler calls the didEndAnimating delegate method.

2021-09-23 17:53 UTC, macdrevx commented on Tests/MapboxMapsTests/Gestures/GestureHandlers/DoubleTapToZoomInGestureHandlerTests.swift
> +        }
This feedback applies throughout this PR since there are multiple places with this same pattern.

2021-09-23 17:53 UTC, macdrevx commented on Tests/MapboxMapsTests/Gestures/GestureHandlers/DoubleTapToZoomInGestureHandlerTests.swift
>      }
Feedback applies to all handlers that animate

2021-09-23 17:55 UTC, macdrevx commented on Tests/MapboxMapsTests/Gestures/GestureHandlers/PanGestureHandlerTests.swift
> +        XCTAssertEqual(gestureType, .pan)
No need to unwrap here - you can compare `.pan` to an optional.

2021-09-23 17:58 UTC, macdrevx commented on Tests/MapboxMapsTests/Gestures/GestureManagerTests.swift
> +        gestureManager.gestureEnded(for: gestureType, willAnimate: true)
Let's pass a random value for `willAnimate` to make this test a bit more robust

2021-09-24 15:50 UTC, macdrevx commented on CHANGELOG.md
> +* Added the public delegate methods ``GestureManagerDelegate.gestureManager(_:didEnd:willAnimate:)` and `GestureManagerDelegate.gestureManager(_:didEndAnimatingFor:)`. ([#697](https://github.com/mapb
```suggestion
* Added the public delegate methods `GestureManagerDelegate.gestureManager(_:didEnd:willAnimate:)` and `GestureManagerDelegate.gestureManager(_:didEndAnimatingFor:)`. ([#697](https://github.com/mapbox/mapbox-maps-ios/pull/697))
```

2021-09-24 15:52 UTC, macdrevx commented on Tests/MapboxMapsTests/Foundation/Camera/Mocks/MockCameraAnimationsManager.swift
> +
Can be removed

2021-09-24 15:52 UTC, macdrevx commented on Tests/MapboxMapsTests/Foundation/Camera/Mocks/MockCameraAnimationsManager.swift
> +
Can be removed

2021-09-24 15:52 UTC, macdrevx commented on Tests/MapboxMapsTests/Foundation/Camera/Mocks/MockCameraAnimationsManager.swift
> +
Can be removed

2021-09-24 15:53 UTC, macdrevx commented on Tests/MapboxMapsTests/Gestures/GestureHandlers/DoubleTapToZoomInGestureHandlerTests.swift
> +        XCTAssertNotNil(cameraAnimationsManager.easeToStub.parameters.first?.completion)
This line can be removed. It's now redundant with the XCTUnwrap below

2021-09-24 15:54 UTC, macdrevx commented on Tests/MapboxMapsTests/Gestures/GestureHandlers/DoubleTapToZoomInGestureHandlerTests.swift
> +        let didAnimateCompletion = try XCTUnwrap(cameraAnimationsManager.easeToStub.parameters.first?.completion)
I think a better name for `didAnimateCompletion` would be `easeToCompletion`

2021-09-24 15:55 UTC, macdrevx commented on Tests/MapboxMapsTests/Gestures/GestureHandlers/DoubleTapToZoomInGestureHandlerTests.swift
> +        XCTAssertNotNil(cameraAnimationsManager.easeToStub.parameters.first?.completion)
Same goes for the other similar tests

2021-09-24 15:55 UTC, macdrevx commented on Tests/MapboxMapsTests/Gestures/GestureHandlers/DoubleTapToZoomInGestureHandlerTests.swift
> +        let didAnimateCompletion = try XCTUnwrap(cameraAnimationsManager.easeToStub.parameters.first?.completion)
Same goes for the other similar tests. Let's name according to the type of animation that's completing

2021-09-24 15:56 UTC, macdrevx commented on Tests/MapboxMapsTests/Gestures/GestureHandlers/PanGestureHandlerTests.swift
> -        delegate = MockGestureHandlerDelegate()
Can undo these changes

2021-09-24 15:57 UTC, macdrevx commented on Tests/MapboxMapsTests/Gestures/GestureHandlers/PanGestureHandlerTests.swift
> +            XCTAssertEqual(delegate.animationEndedStub.invocations.count, 1)
Would like to see this verify the params

2021-09-24 15:58 UTC, macdrevx commented on Tests/MapboxMapsTests/Gestures/GestureManagerTests.swift
> +    func testanimationEnded() {
```suggestion
    func testAnimationEnded() {
```

2021-09-24 16:00 UTC, macdrevx commented on Tests/MapboxMapsTests/Gestures/Mocks/MockGestureManagerDelegate.swift
> +    let gestureEndedStub = Stub<GestureEndedParams, Void>()
Let's update the names here for more consistency:

* Change `gestureBeganStub` to `gestureDidBeginStub` to match the new method signature
* Change `animationEndedStub` to `gestureDidEndAnimatingStub`
* Change `gestureEndedStub` to `gestureDidEndStub`
* Change `GestureEndedParams` to `GestureDidEndParams`

2021-09-24 17:55 UTC, macdrevx approved these changes

2021-09-24 17:57 UTC, merged