[WIP] Update to Common v10.0.0-beta.9 and Core v10.0.0-beta.14
mapbox/mapbox-maps-ios pull request #89
Opened 2021-02-08 22:02 UTC by jmkiley

PRs must be submitted under the terms of our Contributor License Agreement [CLA](https://github.com/mapbox/mapbox-maps-ios/blob/main/CONTRIBUTING.md#contributor-license-agreement).

Fixes: n/a

## Pull request checklist:
 - [ ] Briefly describe the changes in this PR.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
 - [ ] Write tests for all new functionality. If tests were not written, please explain why.
 - [ ] Add example if relevant.
 - [ ] Document any changes to public APIs.
 - [ ] Apply changelog label ('breaking change', 'bug :beetle:', 'build', 'docs', 'feature :green_apple:', 'performance :zap:', 'testing :100:') or use the label 'skip changelog'
 - [ ] Add an entry inside this element for inclusion in the `mapbox-maps-ios` changelog: `<changelog></changelog>`.

### Summary of changes

### User impact (optional)

2021-02-09 15:51 UTC, neelmistry94 approved these changes

2021-02-11 21:14 UTC, nishant-karajgikar requested changes
MapboxCoreMaps should point to `beta-10.0.14.1`

2021-02-12 16:47 UTC, nishant-karajgikar approved these changes

2021-02-12 17:40 UTC, macdrevx requested changes
This should be updating Package.swift and MapboxMaps.podspec too, right?

2021-02-12 18:57 UTC, merged